apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: flux
  labels:
    app: nginx2
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
        date: "+%H:%M:%S %d/%m/%y"
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
